apiVersion: v1
kind: Secret
metadata:
  name: bankly-db-credentials
  namespace: bankly
type: Opaque
data:
  POSTGRES_USER: YmFua2x5dXNlcg== # base64 encoded 'banklyuser'
  POSTGRES_PASSWORD: YmFua2x5cGFzcw== # base64 encoded 'banklypass'
  # Add other secrets like JWT_SECRET here too if your apps use them
  # JWT_SECRET: <base64_encoded_your_jwt_secret_here>